spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jspdb
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 123456
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true